server:
  port: 9001
spring:
  application:
    name: authentication-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/
    fetch-registry: true