server:
  port: 8002
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.huiliang.huiliangcommon.entity
spring:
  application:
    name: Oil-Servce
  redis:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 10
        max-idle: 10
        min-idle: 2
    timeout: 10000
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/