server:
  port: 8000
spring:
  application:
    name: Boundary-Service
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/
